kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: staging
nodes:
  - role: control-plane
    # add port mapping to localhost on 8080 to allow traffic redirection
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP